### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by matheusbsf** [W4RH4WK/Sekiro-Refresh-Rate-Fix#3]
Tried both .dll, game is still locked at 60fps, help

**Comment by W4RH4WK** [comment]
Sorry to hear, I haven't looked at this in ages. Maybe I'll find some time to get back to this, but no promises.

**Comment by k3ys3rsoz3** [comment]
> Tried both .dll, game is still locked at 60fps, help

it still works, just follow the instruction & restart sekiro

**Comment by matheusbsf** [comment]
> > Tried both .dll, game is still locked at 60fps, help
> 
> it still works, just follow the instruction & restart sekiro

I tried a couple of times that day, with no success. Eventually I gave up and downloaded another similar tool that worked for me.

Closing this issue as it seems the problem was only on my end.
